### ISSUE TITLE
文章可评论么

### ISSUE THREAD

**Issue by MAYDAY1993** [cnfeat/blog.io#33]
你好 看了你的博客 想问下文章可评论么 好像没看到带有评论功能 另外 在[https://github.com/cnfeat/blog.io](url)的readme里 你的博客地址写错了  链在了github里。
![2016-12-07 6 06 36](https://cloud.githubusercontent.com/assets/14831051/20963399/27b76e92-bca8-11e6-9bb9-cdec5e11168e.png)

**Comment by cnfeat** [comment]
文章是可以评论的，挂在了 Disquz 中，多谢提醒，已经更新。

**Comment by MAYDAY1993** [comment]
请问一下 看你的博客很简洁  你这个可以直接fork么 站点和评论 需要什么配置 我现在也有个github pages的仓库 目前用的hexo
