### ISSUE TITLE
博主这个模板和简书上面的描述不是一个吧

### ISSUE THREAD

**Issue by caijun-carr** [cnfeat/blog.io#36]
首先还是感谢博主写这么多教程，并且分享出来

然后赞一下博主博客写得真漂亮

现在开始描述遇到的一些问题：
从简书上的教程通过用户名来这里的，但是从日期上看之前的模板应该是已经不在了
然后自己摸索博主的模板但是一直用hexo不成功，后来发现博主应该是基于jekyll做的模板然后试了一下发现成功了，感谢博主！
然后是cname应该是过期了希望有时间删除一下:-D

**Comment by cnfeat** [comment]
已经更新了哈。
