### ISSUE TITLE
请求帮助 

### ISSUE THREAD

**Issue by xuanInitial** [cnfeat/blog.io#44]
最开始绑定的是blog.io这个  然后修改成我自己的 打开页面之后 报错404 页面的图标还是你的头像

**Comment by HarlanZhou** [comment]
去改一下CNAME为你的域名，然后记得解析地址修改，域名购买的地方记得修改解析的

**Comment by symant233** [comment]
请问项目名一定要由blog.io改成自己的么

**Comment by Acheron2012** [comment]
您好，请问如何才能支持markdown语法呢？

**Comment by shenzhuan** [comment]
能加个qq吗 951449465
